from ._cca import _CCA
from .ccalin import calc_ccalin
from .game import calc_game
from .genoja import calc_genoja
from .lagrange import calc_lagrangeminmax
from .alternatingleastsquares import calc_lscca
from .lscca_exact import calc_lscca_exact
from .lvm import calc_lvm
from .numpy import calc_numpy
