import cca_zoo.dcca
import cca_zoo.dccae
import cca_zoo.dvcca
import cca_zoo.kcca
import cca_zoo.alsinnerloop
import cca_zoo.deepwrapper
import cca_zoo.deep_models
import cca_zoo.generate_data
import cca_zoo.wrapper
import cca_zoo.mnist_utils
import cca_zoo.objectives
import cca_zoo.plot_utils
