__all__ = ["alternating_least_squares",
           "DCCAE",
           "DVCCA",
           "KCCA",
           "deep_models",
           "deep",
           "linear",
           "mnist_utils",
           "objectives",
           "plot_utils",
           "objectives"]
