name: Python package

on:
  push:
    branches: [ main, jaxline ]
  pull_request:
    branches: [ main, jaxline]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8
        python -m pip install codecov
        python -m pip install pytest-cov
        python -m pip install -r requirements.txt
    - name: Run Test
      run: pytest --cov-report=xml --cov=ccagame ./ccagame/test/test_pca.py ./ccagame/test/test_pls.py ./ccagame/test/test_cca.py
